---
- include_vars: configs.yml
- name: Create configuration directory
  file:
    path: /home/jbryner/envs/mozdef/bot
    state: directory
    mode: 0755
    owner: jbryner

- name: set the mozdefbot configuration through vars
  copy:
    content: "{{ mozdefbotprodconf }}"
    dest: /home/jbryner/envs/mozdef/bot/mozdefbot.conf
    mode: 0640
    owner: mozdef
#  notify: restart servicename

- name: set the mozdefbot configuration through file copy
  copy:
    src: ./roles/mozdefbot/files/mozdefbot.conf
    dest: /home/jbryner/envs/mozdef/bot/mozdefbot.vaulted.conf
    mode: 0640
    owner: mozdef

- name: copy a dir of config files
  copy:
    src: "{{ item }}"
    dest: /home/jbryner/envs/mozdef/bot/
  with_fileglob:
    - ./roles/mozdefbot/files/dev/*.conf

